Deploy changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,7 +17,6 @@ jobs:
     strategy:
       matrix:
         node-version: [22.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
     - uses: actions/checkout@v4
@@ -26,11 +25,29 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: npm i
-    - run: npm run build --if-present
-    - run: cd ..
-    - run: pm2 stop 0
-    - run: pm2 start 0
-    - run: pm2 save
-    - run: sudo service nginx restart
+    
+    - name: Install node_modules
+      run: npm i
+
+    - name: Project build
+      run: npm run build --if-present
+
+    - name: Change directory
+      run: cd ..
+
+    - name: List PM2 processes
+      run: pm2 list
+
+    - name: Stop PM2 process
+      run: |
+        pm2 stop web-corporativa || echo "Process not found, starting a new one"
+
+    - name: Start PM2 process
+      run: pm2 start ecosystem.config.js --only web-corporativa
+
+    - name: Save PM2 state
+      run: pm2 save
+
+    - name: Restart nginx 
+      run: sudo service nginx restart
 
